name: Python Mise PR Gate
permissions:
  contents: read
  issues: write

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  fast-pr-gate:
    uses: basher83/.github/.github/workflows/python-mise-fast-pr-gate.yml@9f26f1a7c1de5470dac16daa0f38085dc8975fb2 # main
