name: Python Mise PR Gate
permissions:
  contents: read
  issues: write

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  fast-pr-gate:
    uses: basher83/.github/.github/workflows/python-mise-fast-pr-gate.yml@7e2f7cb332c4a9bf185ab84f6f51265d2486c13f # main
