name: Python Mise PR Gate
permissions:
  contents: read
  issues: write

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  fast-pr-gate:
    uses: basher83/.github/.github/workflows/python-mise-fast-pr-gate.yml@b0f38b17192fef9e31416e57a0d08dd67fb1f3cf # main
